[project]
name = "mriutils-in-jax"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "cycler>=0.12.1",
  "jax>=0.4.35",
  "jaxopt>=0.8.3",
  "jaxtyping>=0.2.36",
  "loguru>=0.7.3",
  "matplotlib>=3.9",
  "nibabel>=5.3.2",
  "tqdm>=4.67.1",
]
[project.optional-dependencies]
cli = ["click", "typer", "braceexpand"]
[tool.ruff.lint]
ignore = ["F722"]
