[project]
name = "mriutils-in-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "braceexpand>=0.1.7",
  "click>=8.1.8",
  "cycler>=0.12.1",
  "jax>=0.5.0",
  "jaxopt>=0.8.3",
  "jaxtyping>=0.2.36",
  "loguru>=0.7.3",
  "matplotlib>=3.10.0",
  "nibabel>=5.3.2",
  "tqdm>=4.67.1",
  "typer>=0.15.1",
]
[tool.ruff.lint]
ignore = ["F722"]
